trigger: none
pr: none

# schedules:
# - cron: "0 0,6,12,18 * * *"
#   displayName: Daily build
#   branches:
#     include:
#     - main
#   always: true

variables:
- template: /eng/common/templates/variables/dotnet/common.yml@self
- name: mirrorRepoPrefix
  value: ""

extends:
  template: /eng/common/templates/1es-unofficial.yml@self
  parameters:
    stages:
    - stage: MirrorBaseImages
      displayName: Mirror Base Images
      jobs:
      - template: /eng/pipelines/templates/jobs/mirror-base-images.yml@self
        parameters:
          name: "Public"
          subscriptionsPath: eng/mirror-base-images-subscriptions.json
          repoPrefix: $(mirrorRepoPrefix)
          acr:
            resourceGroup: $(public-mirror.resourceGroup)
            server: $(public-mirror.server)
            serviceConnection: $(public-mirror.serviceConnectionName)
            subscription: $(public-mirror.subscription)
