parameters:
- name: name
  type: string
  default: null
- name: subscriptionsPath
  type: string
  default: null
- name: repoPrefix
  type: string
  default: null
- name: dryRun
  type: boolean
  default: false
- name: acr
  type: object
  default:
    resourceGroup: ''
    server: ''
    serviceConnection: ''
    subscription: ''

jobs:
- job: MirrorBaseImages_${{ parameters.name }}
  displayName: Mirror Base Images - ${{ parameters.name }}
  pool:
    name: NetCore1ESPool-Internal
    image: 1es-ubuntu-2204
    os: linux
  steps:
  - template: /eng/common/templates/steps/init-docker-linux.yml@self
  - ${{ if eq(parameters.dryRun, true) }}:
    - script: echo "##vso[task.setvariable variable=dryRunArg]--dry-run"
  - template: /eng/common/templates/steps/copy-base-images.yml@self
    parameters:
      additionalOptions: "--subscriptions-path '${{ parameters.subscriptionsPath }}'"
      repoPrefix: $(mirrorRepoPrefix)
      acr: ${{ parameters.acr }}
